#!/usr/bin/env php
<?php

# Create The Application
$app = require __DIR__.'/bootstrap/app.php';

# Create The Console Application
$console = $app->make('Sun\Console\Application');


# Run The Console Application
$console->run();
